/* ============================================================================
   BTR PROJECT CATALOG
   ============================================================================
   This file holds every project shown on projects.html.
   To add a new project, copy one of the existing entries below, paste it
   just before the closing  ];  and edit the fields.

   FULL INSTRUCTIONS: see README.md in the repo root.

   FIELDS: title, supervisor, institution, location, email, disciplines[],
           types[], description, dateAdded (required) +
           background, details[], methods, recommended, note (optional)

   ALLOWED DISCIPLINES: Bioinformatics, Biomedical Sciences, Biotechnology,
     Chemistry, Ecology & Fieldwork, Materials Science, Neuroscience,
     Physics, Sustainability, Other
   ALLOWED TYPES: Experimental, Theoretical, Computational, Literature Review
   ============================================================================ */

window.BTR_PROJECTS = [
  {
    title: "X-ray Diffraction for Sustainable Materials Characterization",
    supervisor: "Dr. Marina Borzova",
    institution: "Eindhoven University of Technology",
    location: "Eindhoven",
    email: "m.borzova@tue.nl",
    disciplines: ["Materials Science","Sustainability","Chemistry"],
    types: ["Experimental","Computational"],
    description: "Improve XRD analysis methods for Electric Arc Furnace (EAF) slags as supplementary cementitious materials in the steel industry's sustainability transition.",
    background: "The steel industry accounts for 4–5% of global CO2 and produces >400 Mt of slag annually. EAF slags are heterogeneous and challenging to characterize via XRD due to amorphous phases.",
    details: ["Optimize XRD measurement conditions and instrumental settings","Use internal/external standards","Validate with SEM-EDX and XRF","Explore open-source data analysis approaches","Assess EAF slags as cementitious materials"],
    methods: "XRD, SEM-EDX, XRF, open-source data analysis",
    note: "Part of large collaboration with steel producers and PhD students. No prior hands-on experience required — full training provided. Joint publication potential.",
    dateAdded: "2026-01"
  },
  {
    title: "Modeling Hemodialysis & the Bioartificial Kidney",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Computational"],
    description: "Advance computational models of hemodialysis to design new treatments such as the bioartificial kidney and reduce water usage during dialysis.",
    background: "Collaboration with UMC Utrecht. Uses ODE/PDE/agent-based modelling to optimize kidney treatment devices.",
    methods: "ODEs, PDEs, agent-based models (VCell, Python, Matlab)",
    dateAdded: "2025-11"
  },
  {
    title: "Kidney Physiology: Proximal Tubule & PBPK Modeling",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Computational"],
    description: "Develop in silico models of nephrons capturing toxin transport, drug interactions and metabolism in healthy, CKD and AKI states.",
    details: ["Proximal tubule mitochondria metabolism map","PBPK model (healthy, CKD, AKI)","PBPK model (sex differences)","Linking proximal tubule metabolism and transport","Map of PT transport in physiology and CKD"],
    methods: "ODEs, PDEs (VCell, Python, Matlab)",
    dateAdded: "2025-11"
  },
  {
    title: "Disease Map of Fibrosis",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Computational"],
    description: "Create an extensive visual representation of signaling pathways involved in fibrosis and dynamically model a subset of them.",
    methods: "Pathway mapping, dynamic ODE modelling",
    dateAdded: "2025-11"
  },
  {
    title: "Lung Model for Inhalation Risk Assessment",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Computational"],
    description: "Develop a model assessing the effect of inhaled substances on lung disease, supporting public health risk assessment.",
    note: "Collaboration with RIVM (National Institute for Public Health and the Environment).",
    dateAdded: "2025-11"
  },
  {
    title: "Bone Regeneration with Co-morbidities",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Computational"],
    description: "Model how bone regeneration is affected by co-morbidities to improve treatment strategies for patients with multiple conditions.",
    methods: "ODE/agent-based modelling",
    dateAdded: "2025-11"
  },
  {
    title: "Host-Microbiome Interactions in Aging Female Mice",
    supervisor: "Lena Best & Prof. Christoph Kaleta",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "L.Best@iem.uni-kiel.de",
    disciplines: ["Bioinformatics","Biomedical Sciences"],
    types: ["Computational"],
    description: "Reconstruct gut bacterial genomes from female mice at 3, 15 and 24 months and integrate with host gene expression to study sex-specific aging.",
    background: "Follow-up to Best et al. Nature Microbiology 2025 which identified age-dependent host–microbiome interactions in male mice.",
    details: ["Assemble & annotate metagenomic data","Analyse host RNA-seq from colon and brain","Integrative analysis: metabolic modelling, partial correlation, random forests, WGCNA"],
    methods: "Metagenomics assembly, RNA-seq, metabolic modelling, R/Python",
    note: "Purely computational (dry lab). BSc focuses on Objective 1 OR 2.",
    dateAdded: "2025-11"
  },
  {
    title: "Eukaryotic Metabolic Modeling via Stochastic Petri Nets",
    supervisor: "Dr. Jan Taubenheim",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "j.taubenheim@iem.uni-kiel.de",
    disciplines: ["Bioinformatics"],
    types: ["Computational","Theoretical"],
    description: "Develop an alternative to Flux Balance Analysis for multicellular metabolism using product-inhibition Petri Net models.",
    background: "FBA assumes cellular metabolism is optimised for growth — challenging for multicellular organisms. Petri Nets with product-inhibition feedback offer a new approach.",
    methods: "C++, Python, Petri Net simulation",
    recommended: "Good understanding of C++ and Python; biochemical kinetics",
    dateAdded: "2025-11"
  },
  {
    title: "Machine Learning for Medium Predictions in Metabolic Modeling",
    supervisor: "Dr. Jan Taubenheim",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "j.taubenheim@iem.uni-kiel.de",
    disciplines: ["Bioinformatics"],
    types: ["Computational"],
    description: "Use ML to predict bacterial growth media from genome-derived draft metabolic models, improving culture-free model construction.",
    methods: "R, machine learning, gapseq, SLURM/HPC",
    recommended: "Programming in R; familiarity with ML",
    dateAdded: "2025-11"
  },
  {
    title: "Steroid Hormones & the Gut Microbiome",
    supervisor: "Lena Best & Prof. Christoph Kaleta",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "L.Best@iem.uni-kiel.de",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Computational"],
    description: "Investigate whether menopause-related hormonal changes (and HRT) impact gut microbiome composition using a northern German cohort.",
    methods: "Statistical methods, data visualization, metabolic modelling",
    note: "Purely computational. BSc focuses on objective 1 or 2.",
    dateAdded: "2025-11"
  },
  {
    title: "Metabolite Exchange Networks of the Aging Gut Microbiome",
    supervisor: "Lena Best & Prof. Christoph Kaleta",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "L.Best@iem.uni-kiel.de",
    disciplines: ["Bioinformatics","Biomedical Sciences"],
    types: ["Computational"],
    description: "Use drop-out community simulations to characterise how 'egoistic' bacteria affect microbial metabolite exchange and stability with age.",
    details: ["Integrate age with metabolite exchange data","Network topology analysis","MSc extension: simulate alternative diets"],
    methods: "Network analysis, simulation, R",
    dateAdded: "2025-11"
  },
  {
    title: "Bacterial Niche Formation in Nematostella vectensis Microbiome",
    supervisor: "Dr. Jan Taubenheim & Dr. Johannes Zimmermann",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "j.taubenheim@iem.uni-kiel.de",
    disciplines: ["Bioinformatics","Ecology & Fieldwork"],
    types: ["Computational"],
    description: "Test whether early microbial colonisers of the sea anemone Nematostella create niches for later bacteria via metabolic interactions.",
    details: ["Reconstruct ~60 metabolic models with gapseq","Simulate pairwise interactions with bacarena","Predict growth and exchanged metabolites"],
    methods: "gapseq, bacarena, agent-based modelling, R",
    note: "Master thesis level. Wet-lab partner confirms predictions.",
    dateAdded: "2025-11"
  },
  {
    title: "Curvibacter in Hydra Microbiome Assembly",
    supervisor: "Dr. Jan Taubenheim",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "j.taubenheim@iem.uni-kiel.de",
    disciplines: ["Bioinformatics"],
    types: ["Computational"],
    description: "Use RNA-seq across conditions to study how Curvibacter — the dominant bacterium of the freshwater polyp Hydra — adapts its metabolism.",
    details: ["Differential expression & GSEA","Context-specific metabolic models","Model microbiome–microbiome metabolic interactions"],
    methods: "RNA-seq analysis, metabolic modelling, R/Python",
    dateAdded: "2025-11"
  },
  {
    title: "Interactive Biological Pathways for Rare Diseases",
    supervisor: "Dr. Friederike Ehrhart",
    institution: "Maastricht University — Department of Translational Genomics",
    location: "Maastricht (Universiteitssingel 60, M1.06)",
    email: "friederike.ehrhart@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics","Biomedical Sciences"],
    types: ["Computational"],
    description: "Curate, model and publish molecular pathway diagrams of rare diseases on WikiPathways and analyse omics data with them.",
    background: "Rare diseases (<1:2,000) often lack published pathway models. Pathway diagrams support computational analysis of large datasets.",
    details: ["Identify disease genes from literature","Draw pathways in PathVisio","Publish on WikiPathways","Visualise expression data on pathways","Explore networks in Cytoscape"],
    methods: "Pathway modelling, network analysis, omics data analysis",
    note: "Must be able to install and run PathVisio on your own laptop (>100 MB free).",
    dateAdded: "2025-11"
  },
  {
    title: "Herbarium of the Jochymhof — Limburg Flora",
    supervisor: "Dr. Roy Erkens",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork"],
    types: ["Experimental","Literature Review"],
    description: "Investigate ~1,000 herbarium specimens of the Jochymhof botanical garden in Steyl and write a small data paper.",
    note: "Aim: publication of a data paper.",
    dateAdded: "2025-11"
  },
  {
    title: "Redlisting of Trees and Lianas in Annonaceae",
    supervisor: "Dr. Roy Erkens",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork"],
    types: ["Literature Review","Computational"],
    description: "Make IUCN Red List threat assessments for species in the pantropical plant family Annonaceae.",
    note: "Assessments published as part of yearly IUCN Red List updates. Supervisor is in the Global Tree Assessment group.",
    dateAdded: "2025-11"
  },
  {
    title: "Biogeographical Patterns in Annonaceae using GIS",
    supervisor: "Dr. Roy Erkens",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Bioinformatics"],
    types: ["Computational"],
    description: "Use GIS to investigate what determines the distribution of species in the plant family Annonaceae.",
    note: "Collaboration with University of Montpellier, France.",
    dateAdded: "2025-11"
  },
  {
    title: "Morphological Traits of Guatteria Species",
    supervisor: "Dr. Roy Erkens",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork"],
    types: ["Experimental"],
    description: "Investigate the poorly understood Neotropical genus Guatteria using SEM pollen work or leaf morphometric analyses.",
    methods: "SEM, morphometrics",
    dateAdded: "2025-11"
  },
  {
    title: "Chemical Constituents and Crystals of Tropical Plants",
    supervisor: "Dr. Roy Erkens (with Giuditta Perversi)",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Chemistry"],
    types: ["Experimental","Literature Review"],
    description: "Study the secondary compounds and crystals found in leaves of tropical plant species.",
    dateAdded: "2025-11"
  },
  {
    title: "Network Analysis of Interictal Abnormalities in Stereo-EEG",
    supervisor: "Dr.ir. E.D. Gommer",
    institution: "MUMC+ — Department of Clinical Neurophysiology",
    location: "Maastricht",
    email: "e.gommer@mumc.nl",
    disciplines: ["Neuroscience","Bioinformatics","Biomedical Sciences"],
    types: ["Computational"],
    description: "Implement and evaluate network-based methods to localise the epileptogenic zone using interictal SEEG recordings of drug-resistant epilepsy patients.",
    background: "SEEG provides high-resolution depth recordings. Recent studies suggest epileptogenic regions are embedded in pathological networks with distinctive connectivity.",
    details: ["Identify candidate pathological nodes (spike rates, time-frequency)","Connectivity & network analyses","Characterise interaction with rest of brain"],
    dateAdded: "2026-01"
  },
  {
    title: "Cellular Plant Development Modelling with VirtualLeaf",
    supervisor: "Dr. Ruth Großeholz",
    institution: "Maastricht University",
    location: "Maastricht",
    email: "ruth.grosseholz@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Computational"],
    description: "Use the VirtualLeaf framework to simulate plant tissue growth and developmental processes (e.g. root growth) at cellular level.",
    methods: "VirtualLeaf, computational modelling",
    recommended: "Basic programming. No prior modelling experience required.",
    dateAdded: "2025-11"
  },
  {
    title: "Environmental Responses in Plant Models",
    supervisor: "Dr. Ruth Großeholz",
    institution: "Maastricht University",
    location: "Maastricht",
    email: "ruth.grosseholz@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Computational"],
    description: "Expand existing plant modelling frameworks to incorporate environmental factors such as temperature and light quality.",
    recommended: "Existing programming skills required.",
    dateAdded: "2025-11"
  },
  {
    title: "Multi-Scale Plant Signaling and Response Models",
    supervisor: "Dr. Ruth Großeholz",
    institution: "Maastricht University",
    location: "Maastricht",
    email: "ruth.grosseholz@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Computational"],
    description: "Build models linking molecular signalling and cellular responses, from ODE-based signalling to particle-based protein movement.",
    methods: "ODE modelling, particle-based simulation",
    dateAdded: "2025-11"
  },
  {
    title: "Ancient Technology and Innovation",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Other"],
    types: ["Literature Review","Experimental"],
    description: "Explore the technological, environmental and cultural factors influencing ancient inventions in the eastern Mediterranean.",
    dateAdded: "2025-11"
  },
  {
    title: "Mapping Ancient Landscapes",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Other"],
    types: ["Computational"],
    description: "Map natural resources, transportation routes, biological and geological data to study past human settlement patterns.",
    methods: "ArcGIS, statistics, photogrammetry",
    recommended: "ArcGIS, database design or statistics experience encouraged.",
    dateAdded: "2025-11"
  },
  {
    title: "Human Behavioral Ecology of Past Settlement",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Other"],
    types: ["Computational","Theoretical"],
    description: "Apply ecological models to past human settlement data to understand how landscapes were inhabited and used.",
    dateAdded: "2025-11"
  },
  {
    title: "Experimental Archaeology",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Other"],
    types: ["Experimental"],
    description: "Recreate ancient technologies and structures (e.g. Bronze Age building) to test hypotheses about how things were made and used.",
    dateAdded: "2025-11"
  },
  {
    title: "Ancient Beer: Reconstructing Brewing Recipes",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Chemistry","Other"],
    types: ["Experimental","Literature Review"],
    description: "Reconstruct ancient brewing methods using archaeological, scientific and literary evidence, and document modern recreations.",
    dateAdded: "2025-11"
  },
  {
    title: "Prehistoric Water Management Systems",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Sustainability","Other"],
    types: ["Computational","Literature Review"],
    description: "Examine how prehistoric people manipulated landscapes and built structures to manage rivers and water supplies.",
    dateAdded: "2025-11"
  },
  {
    title: "Tomato Knowledge Graph from Literature Curation",
    supervisor: "Dr. Kumar Saurabh Singh",
    institution: "Brightlands Future Farming Institute",
    location: "Brightlands Campus Greenport Venlo",
    email: "kumarsaurabh.singh@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Computational","Literature Review"],
    description: "Build a curated knowledge graph linking tomato genes, traits, metabolites, pathways, QTLs and disease-resistance using Text2Trait and HARVEST.",
    background: "Tomato literature is vast but scattered. The KG enables novel cross-paper discoveries.",
    details: ["Curate gene→trait, gene→metabolite, QTL→gene relationships","Identify hub genes and consistent associations","Build use-case graphs (pathogens, insects, beneficial microbes)"],
    methods: "Text2Trait (text2trait.com), HARVEST, knowledge graphs",
    note: "Data will be published.",
    dateAdded: "2025-12"
  },
  {
    title: "Normalization Effects on Transcriptomics-Metabolomics Integration",
    supervisor: "Dr. Kumar Saurabh Singh",
    institution: "Brightlands Future Farming Institute",
    location: "Brightlands Campus Greenport Venlo",
    email: "kumarsaurabh.singh@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Computational"],
    description: "Investigate how different normalization strategies (log, Z-score, quantile, CPM/RPKM) affect gene-metabolite correlations in paired multi-omics data.",
    methods: "Multi-omics analysis, statistics, R/Python",
    dateAdded: "2025-12"
  },
  {
    title: "Genomic Boundaries of Plant Biosynthetic Gene Clusters",
    supervisor: "Dr. Kumar Saurabh Singh",
    institution: "Brightlands Future Farming Institute",
    location: "Brightlands Campus Greenport Venlo",
    email: "kumarsaurabh.singh@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Computational"],
    description: "Use linkage disequilibrium patterns to investigate the boundaries of biosynthetic gene clusters (BGCs) producing plant natural products.",
    methods: "Population genomics, linkage disequilibrium, BGC analysis",
    dateAdded: "2025-12"
  },
  {
    title: "Cucumber Transformation Method Development",
    supervisor: "Dr. Xinping Yang",
    institution: "Plant Functional Genomics — Brightlands Greenport Venlo",
    location: "Brightlands Campus Greenport Venlo",
    email: "xinping.yang@maastrichtuniversity.nl",
    disciplines: ["Biotechnology"],
    types: ["Experimental"],
    description: "Develop a robust transformation pipeline for two contrasting cucumber varieties, optimising explant, hormone, medium and Agrobacterium conditions.",
    details: ["Plant tissue culture and explant preparation","Medium recipe & phytohormone formulation","Agrobacterium-mediated transformation","Selection of transformed tissues"],
    methods: "Tissue culture, Agrobacterium transformation",
    note: "Minimum 3 days/week presence in Venlo lab.",
    dateAdded: "2025-11"
  },
  {
    title: "Hormone Reporter Lines for Tomato Regeneration",
    supervisor: "Dr. Xinping Yang",
    institution: "Plant Functional Genomics — Brightlands Greenport Venlo",
    location: "Brightlands Campus Greenport Venlo",
    email: "xinping.yang@maastrichtuniversity.nl",
    disciplines: ["Biotechnology"],
    types: ["Experimental"],
    description: "Generate fluorescent reporter lines visualising auxin/cytokinin signalling during callus induction, shoot initiation and organogenesis in tomato.",
    methods: "Tissue culture, Agrobacterium transformation, fluorescence microscopy",
    note: "Minimum 3 days/week presence in Venlo lab.",
    dateAdded: "2025-11"
  },
  {
    title: "Cytochrome bo3 Oxidase: Substrate/Product Exchange",
    supervisor: "Dr. Ye Gao",
    institution: "M4I Institute — Biochemistry Group",
    location: "Maastricht",
    email: "y.gao@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Biotechnology","Chemistry"],
    types: ["Experimental"],
    description: "Catch intermediate conformations of E. coli cytochrome bo3 quinol oxidase to understand how the enzyme switches between 'open' and 'closed' states.",
    background: "Recent cryo-EM in peptidiscs revealed an 'open' conformation, raising questions about the ~5 ms switching dynamics.",
    details: ["Bioinformatics & molecular modelling","Cloning & recombinant expression in E. coli (ML-I)","Membrane protein purification (IMAC, IEX, GF)","Mass spectrometry & cryo-EM"],
    methods: "Cloning, recombinant expression, IMAC/IEX/Gel Filtration, MS, cryo-EM, SAXS",
    note: "Available September 2026 onwards (Spring 2026 full).",
    dateAdded: "2025-11"
  },
  {
    title: "LCA of Post-Consumer Beverage Carton Recycling",
    supervisor: "Dr. Ali Ghannadzadeh",
    institution: "AMIBM — Aachen-Maastricht Institute for Biobased Materials",
    location: "Brightlands Chemelot Campus",
    email: "ali.ghannadzadeh@maastrichtuniversity.nl",
    disciplines: ["Sustainability","Materials Science"],
    types: ["Computational","Literature Review"],
    description: "Develop a robust EU-wide methodology for calculating recycling rates of fibre-based composite packaging, in collaboration with EXTR:ACT and HEDRA.",
    details: ["Inventory of EU recycling-rate methodologies","Develop dry-weight calculation method","Apply to Germany, Belgium, Spain","Investigate post-separation from residual waste"],
    methods: "Material flow analysis, LCA, Excel simulation tool",
    note: "Industry partnership with EXTR:ACT (EU) and HEDRA (NL). Includes webinar deliverable.",
    dateAdded: "2025-12"
  },
  {
    title: "Dynamic LCA of Microbial Fermentation Bioproducts",
    supervisor: "Dr. Ali Ghannadzadeh",
    institution: "AMIBM — Aachen-Maastricht Institute for Biobased Materials",
    location: "Brightlands Chemelot Campus",
    email: "ali.ghannadzadeh@maastrichtuniversity.nl",
    disciplines: ["Sustainability","Biotechnology"],
    types: ["Computational","Literature Review"],
    description: "Apply the BBM-LCA framework to fermentation projects (PHA bioplastics, single cell protein, biosurfactants) at the University of Manitoba.",
    details: ["PHA biopolymers from C1 carbon (methanol, formic acid, CO2)","Single cell protein from C1","Biosurfactants from lignocellulosic residues","Pulse starch bioconversion","Ethanol/2,3-butanediol from CO2"],
    methods: "Dynamic LCA, BBM-LCA, ISO 14040",
    note: "External collaboration with Dr. Warren Blunt, University of Manitoba, Canada.",
    dateAdded: "2025-12"
  },
  {
    title: "Multi-Disciplinary Sustainability Assessment of Biobased Products",
    supervisor: "Dr. Ali Ghannadzadeh",
    institution: "AMIBM — Aachen-Maastricht Institute for Biobased Materials",
    location: "Brightlands Chemelot Campus",
    email: "ali.ghannadzadeh@maastrichtuniversity.nl",
    disciplines: ["Sustainability"],
    types: ["Computational","Theoretical","Literature Review"],
    description: "Combine Dynamic LCA, Net Ecosystem Exchange, microplastics, circularity, regulations and exergy analysis into a single sustainability framework.",
    methods: "Dynamic LCA, NEE, BBM-LCA, exergy",
    dateAdded: "2025-12"
  },
  {
    title: "Non-Crystallizing Deep Eutectic Solvents",
    supervisor: "Dr. Laura Kollau",
    institution: "Circular Chemical Engineering, UM",
    location: "Brightlands Chemelot Campus",
    email: "l.kollau@maastrichtuniversity.nl",
    disciplines: ["Chemistry","Sustainability"],
    types: ["Experimental"],
    description: "Investigate fundamental properties of non-crystallizing deep eutectic solvents (DESs) as sustainable alternatives.",
    methods: "DSC, 1D and 2D NMR, organic synthesis",
    dateAdded: "2025-11"
  },
  {
    title: "Structure-Based Virtual Screening for Sepsis",
    supervisor: "Dr. Gerry A.F. Nicolaes",
    institution: "Cardiovascular Research Institute Maastricht",
    location: "Maastricht",
    email: "g.nicolaes@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Chemistry"],
    types: ["Computational","Experimental"],
    description: "Use structural bioinformatics and virtual screening to identify drug candidates for severe sepsis.",
    methods: "Structural bioinformatics, molecular docking, virtual screening",
    note: "Limited capacity — interview required.",
    dateAdded: "2025-11"
  },
  {
    title: "Cytotoxic Inflammatory Processes in Sepsis (Histones)",
    supervisor: "Dr. Gerry A.F. Nicolaes",
    institution: "Cardiovascular Research Institute Maastricht",
    location: "Maastricht",
    email: "g.nicolaes@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Chemistry"],
    types: ["Experimental"],
    description: "Study cytotoxicity of extracellular histones and develop prototype drugs to interfere with histone toxicity in sepsis.",
    methods: "Recombinant protein expression, proteomics, MS, cell culture",
    dateAdded: "2025-11"
  },
  {
    title: "Novel Diagnostic Methods for Sepsis at ICU",
    supervisor: "Dr. Gerry A.F. Nicolaes",
    institution: "Cardiovascular Research Institute Maastricht",
    location: "Maastricht",
    email: "g.nicolaes@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences"],
    types: ["Experimental"],
    description: "Develop sensitive and fast methods to assess clinical status of ICU sepsis patients using novel biomarkers.",
    methods: "Protein isolation, bioassays, statistical analysis",
    dateAdded: "2025-11"
  },
];
